### PR TITLE
feat: Misc fixes

### PR DESCRIPTION
**Pull request by amhn**
Fixes: #180
Fixes:  #187
Fixes:  #188
Fixes:  #189
Fixes:  #190
Fixes:  #191
Fixes:  #192
Fixes:  #193
Fixes:  #194
Fixes:  #195
Fixes:  #196
Fixes:  #197

This fixes the above issues. One issue per commit. After every commit, all tests pass.

### CODE REVIEW

**Comment by smutel** [comment]
Hello @amhn. Thanks for this PR. There is a folder called `examples/exports/v3.3/v3.2`. Is-it normal or it is a typo ?

**Comment by amhn** [comment]
That was a typo / wrong git mv call. I pushed a new verstion that fixes this.

**Comment by smutel** [comment]
OK for me. I will just review the commit msg to have a pretty changelog.

**Comment by amhn** [comment]
Feel free to change them as needed. You should be able to push into my branch.

**Pull request merged**
