### PR TITLE
fix: Fix linter deprecation warnings

### LINKED ISSUE #163: golangci-lint warns about deprecated linters
## Summary

The current config causes golangci-lint to emit warnings:
```
  level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
  level=warning msg="[runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner. "
  level=warning msg="[runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused."
  level=warning msg="[runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused."
  level=warning msg="[runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused."
  level=warning msg="[runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'."
  level=warning msg="[linters_context] structcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649."
```

### PR DESCRIPTION
**Pull request by amhn**
Fixes #163

This PR fixes the deprecation warnings from golangci-lint by replacing the linters.

Missing check for d.Set is no longer excluded in the linter config and fixed in all files.

JSON data sources now have a DO NOT EDIT note in the source. With this note some editors e.g. VS Code warn when editing the file.

### CODE REVIEW

**Comment by smutel** [comment]
We have still some linter issues:
```
netbox/resource_netbox_virtualization_vm.go:283:10: Error return value of `d.Set` is not checked (errcheck)
```
=> Fix missing
```
netbox/resource_netbox_virtualization_vm.go:227:1: cyclomatic complexity 37 of func `resourceNetboxVirtualizationVMRead` is high (> 30) (gocyclo)
```
=> Not sure it's a good idea to resolve this right now in this PR
```
netbox/util.go:86:6: func `purgeNestedTagsToNestedTags` is unused (unused)
```
=> Unused function

Also do you why the CI is not crashing with these issues left ?

**Comment by amhn** [comment]
For the first 2 I have prepared a commit. Unfortunately this commit is based on #161. I will create an issue after that one is merged.

The third is addressed in #161

```
reviewdog: No results found for "golangci". 3 results found outside diff.
```
This is the reason these are not errors. The second one should have been an error in #158. Not sure why this was not caught there.

**Comment by smutel** [comment]
So can we merge https://github.com/smutel/terraform-provider-netbox/pull/161 first ?

**Comment by amhn** [comment]
```
  reviewdog: No results found for "golangci". 0 results found outside diff.
```
:smile:

**Comment by smutel** [comment]
Wonderful :+1:

**Pull request merged**
