### PR TITLE
Add ability to return json objects of Netbox list endpoints

### PR DESCRIPTION
**Pull request by sc0ttes**
Not currently handling pagination but figured this was a good start just to get it running for the non-data-center user.

Output in Terraform looks as so:

```dcim_sites_list = [
  {
    "circuit_count" = 1
    "created" = "2020-10-10"
    "custom_fields" = {}
    "device_count" = 2
    "id" = 1
    "last_updated" = "2020-10-10T12:30:20.992Z"
    "name" = "Office"
    "region" = {
      "id" = 1
      "name" = "East"
      "slug" = "east"
      "url" = "http://172.17.0.1:8000/api/dcim/regions/1/"
    }
    "slug" = "office"
    "status" = {
      "label" = "Active"
      "value" = "active"
    }
    "url" = "http://172.17.0.1:8000/api/dcim/sites/1/"
  },
  {
    "created" = "2020-10-10"
    "custom_fields" = {}
    "device_count" = 1
    "id" = 2
    "last_updated" = "2020-10-10T12:30:42.912Z"
    "name" = "Office2"
    "region" = {
      "id" = 2
      "name" = "West"
      "slug" = "West"
      "url" = "http://172.17.0.1:8000/api/dcim/regions/2/"
    }
    "slug" = "office2"
    "status" = {
      "label" = "Active"
      "value" = "active"
    }
    "url" = "http://172.17.0.1:8000/api/dcim/sites/2/"
  },
]
```

### CODE REVIEW

**Comment by smutel** [comment]
Hello,

Could you please share some code to see how to use this feature ?

Thanks.

**Comment by sc0ttes** [comment]
Hey Samuel,

I haven't actually tried this with vSphere because I haven't set it up yet but this is roughly what I was thinking:

```
terraform {
  required_providers {
    netbox = {
      source = "smutel/netbox"
    }
    vsphere = {
      source = "hashicorp/vsphere"
    }
  }
}

provider "netbox" {
  # Environment variable NETBOX_URL
  url = "172.17.0.1:8000"

  # Environment variable NETBOX_TOKEN
  token = "0123456789abcdef0123456789abcdef01234567"

  # Environment variable NETBOX_SCHEME
  scheme = "http"
}

data "netbox_json_virtualization_virtual-machines_list" "all_vms" {}

provider "vsphere" {
  user           = "user"
  password       = "pass"
  vsphere_server = "172.17.0.5"

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "dc1"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore1"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_compute_cluster" "cluster" {
  name          = "cluster1"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "public"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name             = "${element(data.netbox_json_virtualization_virtual-machines_list.all_vms, 0).name}"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = element(data.netbox_json_virtualization_virtual-machines_list.all_vms, 0).vcpus
  memory   = 1024
  guest_id = "other3xLinux64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size  = 20
  }
}
```

Notice the vm's name and num_cpus (could be extended to memory, disk size, network interface/mac, etc). I would like to build my resources using Netbox as my single source-of-truth where I would loop through all the elements returned from Netbox and build the resources in Terraform from them.

Welcome any thoughts or concerns and any changes I need to make. Noticed it's failing linting in large part due to Json vs JSON -- I can fix it or an exception could be added for allowing "Json".

I wrote a bash script to generate all the files using an input list that includes all the Netbox endpoints. Happy to include it in a "helpers" folder or similar as well.

Regards,
Scott

**Comment by smutel** [comment]
Thank you for your explanation. It's clear for me now.

Please find below the things to do before merging:
* Remove the CHANGELOG update (I will do it when I will create a new release)
* Don't use "-" in filename, use "_" instead
* Fix the LINT warning, I am not fan for an exception at this time
* Update the docs/ folder to document your change
* Add your script to generate this file in a folder called utils

**Comment by smutel** [comment]
Most of the provider set an exception for d.Set like in the [openstack provider.](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/5f8a9fbcacbda50656cdc5b94af3764f3834cfde/.golangci.yml#L57)
What do you think ?

**Comment by sc0ttes** [comment]
Sounds good with me -- just added to the lint rules. Thanks for the reference!

**Comment by smutel** [comment]
Thank you for your changes.

Last things before merging:
- Remove your last commit 8b3d0100955b8017a9c9c4a3376d6ece9e863d31
- Fixup all your commits with message "feat: **A**dd ability to return json objects of all endpoints"

**Comment by sc0ttes** [comment]
>     * Fixup all your commits with message "feat: Add ability to return json objects of all endpoints"

Do you mean for me to rebase and reword all previous commits with that?

**Comment by smutel** [comment]
Yes please. The CHANGELOG is generated from the commits.

**Comment by sc0ttes** [comment]
I don't believe this is what you were looking for but I'm not sure how else I can change all the old commit messages without rebasing every commit along the way.

**Comment by smutel** [comment]
> I don't believe this is what you were looking for but I'm not sure how else I can change all the old commit messages without rebasing every commit along the way. Happy to also just start over again and create a new branch with all the changes in a single commit and then open a pull request.

Happy to also just start over again and create a new branch with all the changes in a single commit and then open a pull request. => yes please

**Comment by smutel** [comment]
Hello @sc0ttes,

I need to update the provider for Netbox 3.0.
Could you please tell me how to update the `netbox_list_endpoints.txt file` ?

Thanks.

**Pull request closed without merging**
