### PR TITLE
feat: Add an option to initialize the client with the private key

### PR DESCRIPTION
**Pull request by BonySmoke**
In the NetBox version prior to 3.0, to read encoded data from secrets, we would need to include the session key to a request.
The purpose of the PR is to add a possibility to initialize the client with the private key.

### CODE REVIEW

**Review by smutel — DISMISSED** [review]
LGTM

**Comment by smutel** [comment]
Could you please fixup all your commits with only one "Add an option to initialize the client with the private key" ?
This will be use to generate the changelog.

**Comment by BonySmoke** [comment]
A would like to clarify something:
Do I understand correctly that I need to squash these commits into one and push it with the message you mentioned?
So I would do something like this
```
git rebase -i HEAD~6 feat/add-private-key
change all commits from pick to squash
change commit message to "feat: Add an option to initialize the client with the private key"
git push origin feat/add-private-key --force
```
Or there is something else I need to do?

**Comment by BonySmoke** [comment]
So, I actually needed to leave the first one as pick and change all the others to squash:)
Is it good now?

**Review by smutel — APPROVED** [review]

**Pull request merged**
