### PR TITLE
feat: Testing and resources

### LINKED ISSUE #166: Add resources to enable self-sustained tests
## Summary

The following tests are needed to be able to write tests, that work with a fresh netbox instance:
netbox_virtualization_cluster
netbox_virtualization_cluster_type
netbox_virtualization_cluster_group
netbox_extras_custom_field
netbox_extras_tag
netbox_dcim_site
netbox_ipam_asn
netbox_dcim_platform
netbox_dcim_device_role
netbox_dcim_manufacturer
netbox_ipam_rir

### Terraform code

```hcl

```

### PR DESCRIPTION
**Pull request by amhn**
fixes #166 
This PR is bit on the large side. It depends on #149 and #154. There are a bunch of new resources added, one per commit.

This is done mostly to be able to run the tests on a new docker-netbox container.

If you want I can create PRs per resource, although this would be a bit more work as some of the commits depend on each other (mostly because the tests use resources introduced in earlier commits).

### CODE REVIEW

**Comment by amhn** [comment]
@smutel  Did you have time to look at this? Or did you not see it? I just noticed this PR was not assigned to you.

Is this something that could be merged?

**Comment by smutel** [comment]
Thanks for this PR.

Could you please split this PR in several piece:
- This PR should contain only new resources with tests
- A new PR for each other file changed

Also please take a look at the pipeline check result.

**Comment by amhn** [comment]
This branch now only contains new resources (after #164 is merged).

Linter warnings are fixed. I would like to rework all new resources in the style of dcim_site/virtualization_vm before merging. I think this could be ready later today.

**Comment by amhn** [comment]
All cleaned up and all tests pass you can either merge this PR directly of first merge #164. That PR is included here.

**Pull request merged**
