### PR TITLE
fix: Enable http transport connection reuse

### PR DESCRIPTION
**Pull request by amhn**
fixes: #206 
- Connection reuse does seem to break with a cloned http default transport.
- Simplify client setup by removing custom types
- Remove transport struct

Reasons to remove transport struct and simplify client setup
- I did experiment a lot and was not able to get connection usage down with a cloned http default transport.
- In transport.RoundTrip base was not saved after setup. This lead to creation of multiple transport. Fixing this did not decrease connection usage.
- The functionality to add custom headers to the transport seems to be unused.
- Adding client certs is not possible yet and not supported by netbox AFAIK

This allowed to use the default client with the default transport and. if insecure is set,  with a simplified tls.Config. I did not check the behaviour with insecure = true, as I do not have a setup for this. http and https with a trusted cert is confirmed working.

If you think this is too big of a change, the following should work too:
```go
diff --git a/netbox/provider.go b/netbox/provider.go
index 3a984b20..a8e578fa 100644
--- a/netbox/provider.go
+++ b/netbox/provider.go
@@ -251,9 +251,10 @@ func (t *transport) RoundTrip(req *http.Request) (*http.Response, error) {
        base := t.base
        if base == nil {
                // init an http.Transport with TLSOptions
-               customTransport := http.DefaultTransport.(*http.Transport).Clone()
+               customTransport := http.DefaultTransport.(*http.Transport)
                customTransport.TLSClientConfig = t.TLSClientConfig
                base = customTransport
+               t.base = base
        }
        return base.RoundTrip(req)
 }
```

### CODE REVIEW

**Comment by smutel** [comment]
Hello @amhn, could you please rebase and we will see if the linter is ok.

**Comment by amhn** [comment]
Done. Lint error stays. Is NETBOX_INSECURE set in the CI-Variables? On my machine I do not get this error.

(Sorry. Took me a while to react, occupied with other things.)

**Comment by amhn** [comment]
Changing the way to handle insecure seems to have helped. I.e. not creating a new TLSConfig but setting InsecureSkipVerify on the existing.

I have NOT tested this change with an invalid certificate.

**Review by smutel — APPROVED** [review]
LGTM

**Pull request merged**
