### PR TITLE
feat: netbox request params and provider argument

### PR DESCRIPTION
**Pull request by BonySmoke**
- Add the filter block to the following data resources: secrets_list, clusters_list, devices_list
- Add the devicename argument to interfaces_list
- Add the limit param to secrets_list, clusters_list, devices_list, interfaces_list
- Add an option to initialize the client with the private key to read encoded data like secrets
- Document the changes
The changes have been tested with NetBox version 2.10.4.
----
I will be glad to make any changes if needed.

### CODE REVIEW

**Comment by smutel** [comment]
Thank you for your PR.

Could you please split your request in several PR:
1. Add the filter block to some JSON data resources
    *  Perhaps the best is to store some common part in util.go
2. Add the devicename argument to interfaces_list
    * Could not be part of a filter instead of a specific behavior ?
3. Add the limit param to secrets_list, clusters_list, devices_list, interfaces_list
    * Is-it possible to add it to all ?
4. Add an option to initialize the client with the private key to read encoded data like secrets

Small PRs are easier to review and comment. Thanks.

**Comment by BonySmoke** [comment]
Thank you for the suggestions. I will proceed as you mentioned.

I would like to clarify something regarding the PRs to avoid any issues:
1)  `Add the filter block to some JSON data resources. Perhaps the best is to store some common part in util.go`
I was thinking about this for a while now, but I'm not sure how it can be implemented with the params.
As I understand, it would be great to have one function that could create params for any resource type (like secrets or dcim).
However, the issue here is that we will need to pass the type of the params to the function and we cannot change the variable type dynamically.
So for example, the function arguments can look like this:
```go
func filterDataResource(params *secrets.SecretsSecretsListParams, filter interface{}, ok bool)
```
But I don't see a way for us to dynamically change the param type in this case.

Could you please tell me more about your vision and I will try to implement it?

Also, I would like to mention that my implementation is basically based on this terraform provider example:
https://github.com/e-breuninger/terraform-provider-netbox/blob/master/netbox/data_source_netbox_interfaces.go

2) `Add the devicename argument to interfaces_list`
It can surely be a part of the filter. I will create the filter set for the data resource as well.

3) `Add the limit param to secrets_list, clusters_list, devices_list, interfaces_list`
There are quite many data resources but I will add the limit param to all.

**Comment by smutel** [comment]
1. I don't see at this time how to avoid this concern so ok for you code
2. OK
3. You have a script in utils folder called `netbox_generate_json_datasources.sh` and a list of endpoint in file called `netbox_list_endpoints.txt`. You can use it to generate all json go files in on step

**Comment by smutel** [comment]
Can I close this PR?

**Comment by BonySmoke** [comment]
Yes, sure.
Once you merge your PR for the upgrade to 2.11, I will create a PR for filters. I want to generate it the same way as with the limit param and just add some custom options to some resources.

**Pull request closed without merging**
